---
name: terraform-provider-credhub
platforms:
- darwin/amd64
- linux/amd64
- windows/amd64
- linux/386
- windows/386
metadata:
  shortname: credhub
asset_template: "{{.Name}}_{{.OS}}_{{.Arch}}"
install_path: "{{.Home}}/.terraform.d/providers/{{.Name}}"
install:
  path: bin/aptgit-install.sh
