issues:
  exclude-rules:
    # Exclude issues bypassing staticcheck.conf
    - linters:
        - staticcheck
      text: "SA1019:"
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - govet
    - bodyclose

linters-settings:
  gofmt:
    simplify: false

run:
  tests: false
