language: go
go:
  - "1.15"
install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - export GO111MODULE=on
script:
  - |
    if [ "$(go fmt ./...)"]; then
      echo "You need to run `go fmt`"
      exit 1
    fi
  - go test `go list ./... | grep -v vendor` -v
after_success:
  - bin/build-all.sh
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
